project:
  type: website


website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href : projects/project.qmd
        text: Projects
        menu:
          - href: projects/Customer Segmentation/suncounty-customer-segmentation.qmd
            text: Sun Country Segmentation Analysis
          - href: projects/yelp-restaurant-ratings-analysis.qmd
            text: Yelp Analysis
          - href: projects/amazon-product-analysis.qmd
            text: Amazon Product Reviews Sentiment Analysis
          - href: projects/bank-churn-prediction.qmd
            text: Bank Churn Prediction
          - href: projects/netflix-recommendation.qmd
            text: Netflix Recommendation System

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    




