project:
  type: website


website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/suncounty.qmd
            text: Sun Country Segmentation
          - href: projects/yelp_analysis.qmd
            text: Yelp Analysis
          - href: projects/amazon_customer_analysis.qmd
            text: Amazon Customer Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    




